require("custom.configs.harpoon")
require("custom.configs.undotree")
require("custom.configs.fugitive")
require("custom.configs.nvim-tree")
require("custom.configs.catppuccin")
require("custom.configs.neogit")
require("custom.configs.lualine")
